services:
  - type: web
    name: portfolio-backend
    runtime: node
    plan: free
    rootDir: portfolio-backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: CORS_WHITELIST
        value: "http://localhost:3000,https://portfolio-flame-kappa-zxslojpg4l.vercel.app,*"
